### ISSUE TITLE
Extracting .bytes not directly possible

### ISSUE THREAD

**Issue by sroebert** [vapor/node#24]
Because of the `.bytes` type being an array. It is very hard to properly extract this from a `Node`. If you use the normal extract method. Instead of extracting bytes, it will try to extract an `Node` array of numbers. This is understandable, but very inconvenient.

Would it be an idea, to change the `[UInt8]` from `.bytes` into `Data` from Foundation? I now this has a bit of overhead, compared to using an array directly. It does however make more sense, looking at Foundation and it will make extracting possible, as it is a completely different type.

**Comment by tanner0101** [comment]
Could you provide an example of the code that is failing here? 

I see the issue, but I think there could be an easier way to fix it. Using Bytes instead of Data was deliberate since there are a lot of disadvantages to Data.

**Comment by sroebert** [comment]
https://github.com/sroebert/postgresql-driver/blob/bugfix/schemaUnitTest/Tests/FluentPostgreSQLTests/SchemaTests.swift#L58

So it looks like this:

``` swift
guard let dataNode = node["data"], case .bytes(let dataBytes) = dataNode else {
    throw NodeError.unableToConvert(node: nil, expected: "Node.bytes")
}
data = dataBytes
```

This could obviously be some kind of extension, but it is not as easy as simply calling extract.

**Comment by tanner0101** [comment]
I see. @LoganWright any ideas here?

**Comment by loganwright** [comment]
@tannernelson @sroebert I think this is a pretty tricky issue under the hood because if user has something like `let foo: [UInt8]`, it's not really possible for us to tell if they're expecting an array of integers, or a byte array.

Let me think if there's some trickery we can do internally to get this working, if not, it might be worth an official method like `extractBytes()` since we've opted to have bytes be explicit elsewhere.

**Comment by loganwright** [comment]
We're adding an explicit bytes accessor at the lower level which is intended to apply to `.bytes([UInt8])` and will likely also provide a byte representation of Strings 👍

**Comment by loganwright** [comment]
The bytes variable field has been added in 2.+ in conformance with Polymorphic
