### ISSUE TITLE
Converting node object to string

### ISSUE THREAD

**Issue by hhanesand** [vapor/node#25]
Is there a reliable way to convert all (or most) node instances to a human textual representation? All the methods I've tried leave too many escape characters or type information in the string...

For example, `node.toJSON().object` produces `[\"name\": JSON.JSON(node: Node.Node.string(\"name\"))]`, however I'd like it to just be `["name" : "name"]`

Any ideas?

**Comment by tanner0101** [comment]
Encoding to JSON with pretty print enabled would give you a good printout.

```swift
// your node object
let foo: Node = .string("hi")

// convert to JSON
import JSON
let json = try JSON(node: foo)

// output pretty print
let output = try json.serialize(prettyPrint: true)
print(output)
```

**Comment by hhanesand** [comment]
Thanks!
