### ISSUE TITLE
Why can makeNode throw an error? When would that ever happen?

### ISSUE THREAD

**Issue by Evertt** [vapor/node#26]
I can totally see why the init of `NodeInitializable` needs to be able to throw, because you can never know if the `Node` you'll get is a valid `Node`. However, I don't see why the `makeNode` of `NodeRepresentable` should be able to throw.

If you make a type that conforms to `NodeRepresentable` then you know your variables should be compatible with the possible types of `Node` right?

If we can't think of a use-case where throwing is necessary then I vote to remove that. The less I have to worry about potentially throwing methods the better imo.

**Comment by tanner0101** [comment]
Perhaps one of the values you require when saving to the DB is `nil`. 

But mostly it was done for parity between the init and make methods.

**Comment by Evertt** [comment]
> Perhaps one of the values you require when saving to the DB is `nil`.

I don't agree with that. The class that implements `makeNode` should not have to know what that node will be used for and therefor it shouldn't have to decide on whether the consumer of that node would consider it to be a valid node. The `makeNode` method should do nothing more than to return a `Node` representation of the instance. Making `makeNode` throwable is like making the `description` var of `CustomStringConvertible` throwable (not that that's possible, but you get my point). If an entity requires some value not to be `nil` then it should enforce that before `makeNode` is called, i.e. by not making that value an optional. Don't you think?

> But mostly it was done for parity between the init and make methods.

I can imagine that it feels better to have both of those throwable, because of symmetry which humans innately love. But I think the costs are far higher. Now every time I (or another developer) needs to use `makeNode` we either have to make our method throw as well or we need to write `try!` every time. Both those options make the code less clean. Mostly, it's just very confusing if a method says it can throw an error when it actually never does (or even should).

Therefor, I would **really** appreciate it if we could remove the `throws` from `makeNode`. Would you be willing to accept a PR from me that removes it? Then I'm also willing to remove the `try` from every other method in every vapor repo that uses the `makeNode` method.

**Comment by loganwright** [comment]
Removing `try` is an acceptable change speaking purely from an API perspective since it would just be compiler warnings.

Before we do that, is this a plausible scenario. A model fetches a linked model from a database before creating a more complex Node object, this fetch is failable and would be a involved in the makeNode operation. In this scenario, throwing is easier to be honest about this.

One thing I've done in the past @Evertt is to not make it throw on models that don't throw. For example, if you call `"".makeNode()` it won't try to throw because the implementation on `String` explicitly does not throw. We only have it throw when the underlying type is unknown.

**Comment by Evertt** [comment]
> Before we do that, is this a plausible scenario. A model fetches a linked model from a database before creating a more complex Node object, this fetch is failable and would be a involved in the makeNode operation. In this scenario, throwing is easier to be honest about this.

Hmm yes, that does sound at least somewhat reasonable. Shit. :-P

> One thing I've done in the past @Evertt is to not make it throw on models that don't throw. For example, if you call "".makeNode() it won't try to throw because the implementation on String explicitly does not throw. We only have it throw when the underlying type is unknown.

Oh right, I forgot you aren't actually obligated to implement the method with `throws`.
