### ISSUE TITLE
help with NodeError.unableToConvert / extract method

### ISSUE THREAD

**Issue by gperdomor** [vapor/node#30]
Hi... I have a `NodeConvertible` class, in the `init` currently i have one `do/try/catch`for every required key:

```swift
do {
    id = try node.extract("id")
} catch NodeError.unableToConvert {
    throw CustomError.noId
}

do {
    type =  try node.extract("type")
} catch NodeError.unableToConvert {
    throw CustomError.noType
}
```

but I think is more cleaner having something like this: 

```swift
do {
    id = try node.extract("id")
    type =  try node.extract("type")
} catch {
    switch( something ) {
        case "id":
            throw CustomError.noId
        break
        case "type":
             throw CustomError.noType
        break
    }
}
```

How can I do that?

**Comment by loganwright** [comment]
@gperdomor we're working on an update now that will give you the keys that failed in the error message 👍 

Should be released within the next 2 weeks conservatively!

**Comment by gperdomor** [comment]
@LoganWright thanks :D

**Comment by loganwright** [comment]
@gperdomor it's merged into latest Master, but we have a longer road now of updates to get it integrated into Vapor for more general use. Feel free to try it out and let us know what you think!
