### ISSUE TITLE
makeNode(context: ...)

### ISSUE THREAD

**Issue by tanner0101** [vapor/node#34]
Currently `makeNode(context: Context)` requires some initialized object to be passed as a context.

It would be nice to pass a Type such as `JSON` or `Model` to Context, showing what type the Node is being used to create.

This way the method could be implemented like:

```swift
switch context {
case Model.self:
   return modelNode // for saving to db
case JSON.self:
   return jsonNode // for http response
}
```

I don't know how feasible this is, but this or something similar to this would be ideal.

**Comment by vzsg** [comment]
Enum cases as context look and feel pretty clean IMHO.

**Comment by tanner0101** [comment]
Enums would be great if it weren't for the fact that adding cases can break code (exhaustive switches don't need a default).
Because of this we're tending to avoid enums wherever possible.

**Comment by tanner0101** [comment]
Fixed in JSON and Fluent updates.

See https://github.com/vapor/node/issues/35
