### ISSUE TITLE
Make a node with JSON

### ISSUE THREAD

**Issue by dalu93** [vapor/node#35]
Hi,
I'm experiencing some problems creating a `Node` using an array of `JSON`.

Here is the code I'm using for make my life easier

```swift
struct JSONArray<Element: JSONRepresentable>: ResponseRepresentable {
    let elements: [Element]
    let key: String?
    
    init(_ elements: [Element], key: String? = nil) {
        self.elements = elements
        self.key = key
    }
    
    func makeResponse() throws -> Response {
        let elementsJSON = try elements.map { try $0.makeJSON() }
        if let key = key {
            let node = try Node(node: [
                key: elementsJSON.makeNode()
            ])
            
            return try JSON(node).makeResponse()
        } else {
            return try JSON(elementsJSON.makeNode()).makeResponse()
        }
    }
}
```
But I actually have to convert the array of my objects in array of JSON, then convert it to a node, encapsulate in a node and return the JSON as `ResourceRepresentable` 🤔

See the original question [here](https://github.com/vapor/vapor/issues/810)

**Comment by tanner0101** [comment]
@dalu93 Fluent [1.3.5](https://github.com/vapor/fluent/releases/tag/1.3.5) adds a `DatabaseContext` and JSON [1.0.4](https://github.com/vapor/json/releases/tag/1.0.4) adds a `JSONContext`.
