### ISSUE TITLE
NodeRepresentable string subscript setter

### ISSUE THREAD

**Issue by tanner0101** [vapor/node#36]
Would it be possible to set subscript on node object with something `NodeRepresentable`?

 ```swift
data["password"] = try hash.make(password).makeNode()
```

Removing the need to specify `.makeNode()` here would be nice.

**Comment by loganwright** [comment]
Unfortunately, subscripts can't throw yet, and we can't infer non-throwing implementations of the protocol, so at this time, we're kind of stuck
