### ISSUE TITLE
Documentation circle

### ISSUE THREAD

**Issue by treaves** [vapor/node#42]
The documentation for this module says to read the main Vapor documentation (with a link), and the main documentation says to read the documentation for this module here(with a link). It's a circular reference, with no actual documentation.

**Comment by loganwright** [comment]
@treaves whoops, we must've lost something somewhere. We'll pull the docs out of commit history and put em up, thanks for letting us know.

**Comment by kylebrowning** [comment]
This still seems to be an issue,

**Comment by loganwright** [comment]
@kylebrowning and others, should've posted here. We've changed quite a few paradigms, and we're really close to releasing 2.0. We'll have more thorough documentation around Node at that point w/ the updated changes 👍
