### ISSUE TITLE
DateFormatters aren't compatible due to relying on defaults

### ISSUE THREAD

**Issue by iAlirezaKML** [vapor/node#64]
In `Date+Convertible.swift`, some `DateFormatter`s are defined, but they're not compatible with themselves.
In case for `iso8601` the `locale` is set to `en_US_POSIX` but the others aren't, which leads to wrong conversion between dates. For example I use `Persian` calendar in my mac, when trying to save a date, it's ok in DB. but when I try to create `iso8601` format for JSON, it gives an invalid date (2017 yields in 2638).

**Comment by loganwright** [comment]
@iAlirezaKML to clarify, the proposed solution here, would be to define the locale to be `en_US_POSIX` everywhere
