### ISSUE TITLE
Same-type requirement makes generic parameter 'Element' non-generic

### ISSUE THREAD

**Issue by runewell** [vapor/node#74]
When building the node module I get the following error regarding an Array extension in the FuzzyConverter.swift file.

/JSON/Packages/Node-2.0.0/Sources/Node/Fuzzy/FuzzyConverter.swift:21:40: error: same-type requirement makes generic parameter 'Element' non-generic

Any thoughts on how to resolve this? Am I missing an extension file from another project?

**Comment by tanner0101** [comment]
Node 2 requires Swift 3.1. https://docs.vapor.codes/2.0/getting-started/install-on-macos/#install-vapor
