### ISSUE TITLE
Build fails with Use of undeclared type 'ExpressibleByStringLiteral' extension Node: ExpressibleByStringLiteral

### ISSUE THREAD

**Issue by shanezilla** [vapor/node#8]
git clone a fresh copy of master and ran a build with 'swift build' which fails. Output follows.

xcodebuild -version
Xcode 8.0
Build version 8S174q

swift --version
Apple Swift version 3.0 (swiftlang-800.0.34.6 clang-800.0.33)
Target: x86_64-apple-macosx10.9

swift build 
Compile Swift Module 'Node' (20 sources)
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Utilities/Errors.swift:13:56: error: use of undeclared type 'Error'
                                   to type: T.Type) -> Error {
                                                       ^~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Number/Number.swift:140:24: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node.Number: ExpressibleByIntegerLiteral {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Number/Number.swift:146:24: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node.Number: ExpressibleByFloatLiteral {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Utilities/Errors.swift:13:56: error: use of undeclared type 'Error'
                                   to type: T.Type) -> Error {
                                                       ^~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Number/Number.swift:140:24: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node.Number: ExpressibleByIntegerLiteral {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Number/Number.swift:146:24: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node.Number: ExpressibleByFloatLiteral {
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Utilities/Errors.swift:13:56: error: use of undeclared type 'Error'
                                   to type: T.Type) -> Error {
                                                       ^~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:23:33: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Dictionary where Key: ExpressibleByStringLiteral, Value: NodeRepresentable {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:1:17: error: use of undeclared type 'ExpressibleByNilLiteral'
extension Node: ExpressibleByNilLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:7:17: error: use of undeclared type 'ExpressibleByBooleanLiteral'
extension Node: ExpressibleByBooleanLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:13:17: error: use of undeclared type 'ExpressibleByIntegerLiteral'
extension Node: ExpressibleByIntegerLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:19:17: error: use of undeclared type 'ExpressibleByFloatLiteral'
extension Node: ExpressibleByFloatLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:25:17: error: use of undeclared type 'ExpressibleByStringLiteral'
extension Node: ExpressibleByStringLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:39:17: error: use of undeclared type 'ExpressibleByArrayLiteral'
extension Node: ExpressibleByArrayLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Core/Node+Literals.swift:45:17: error: use of undeclared type 'ExpressibleByDictionaryLiteral'
extension Node: ExpressibleByDictionaryLiteral {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/shanec/Dropbox/wrk/git/external/mysql/mysql-0.3.1/node/Sources/Node/Convertible/Sequence+Convertible.swift:33:67: error: default argument value of type 'T.Type' cannot be converted to type 'T.Type'
    public func converted<T: NodeInitializable>(to type: T.Type = T.self) throws -> T {
                                                                  ^
<unknown>:0: error: build had 1 command failures

**Comment by loganwright** [comment]
Hi @shanezilla this appears to be the swift version shipped w/ beta3, to properly build Node, (and all updated Vapor packages), we'll need to be on the `DEVELOPMENT-SNAPSHOT-07-25`.

Let me know if you still have problems.

**Comment by shanezilla** [comment]
Ah. Got it. Thanks!
