### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by Evertt** [vapor/node#83]
I would appreciate some documentation of the new Node. I'm reading through then code and I'm not able to understand every choice yet. For example, what's the purpose of `Fuzzy` exactly? Why are `Node` and `StructuredData` separate things while they also seem to be tightly coupled? IIRC in the previous version there used to be lots of `converted` functions everywhere and now I don't see them anymore. Did you guys find a more clean / flexible way to cover that functionality or did you just drop part of that functionality.

**Comment by tanner0101** [comment]
The plan is to remove all of that for Swift 4. The fuzzy stuff is a temporary fix while we wait for conditional conformance. I don't see a point in documenting until we get that. How to use `.get` and `.set` is documented fairly extensively already and that is really all most apps should need.

**Comment by tanner0101** [comment]
Also, `converted()` is still available and works the same iirc.

**Comment by Evertt** [comment]
@tanner0101 you mean you'll remove Node in favor of using the `Codable` protocol and making encoders / decoders?

**Comment by tanner0101** [comment]
Node will stay, just `.fuzzy` will be removed. And a lot of other stuff we use internally to make that work.
