### ISSUE TITLE
Conversion to/from system libraries type

### ISSUE THREAD

**Issue by valeriomazzeo** [vapor/node#95]
Node is missing bridging methods to and from system libraries.

It would definitely be useful to be able to convert any `Node`, `JSON`, `StructuredData` to `Any` / `[String: Any]`.

This would make possible to bridge objects created using vapor, to system libraries such as `JSONSerialization`, etc.

It could look something like this:

```swift
public extension StructuredData {

    public init(any: Any) {

        switch any {

        case let value as [String: Any]:
            self = .object(value.mapValues { StructuredData(any: $0) })

        case let value as [Any]:
            self = .array(value.map { StructuredData(any: $0) })

        case let value as Bool:
            self = .bool(value)

        case let value as [UInt8]:
            self = .bytes(value)

        case let value as Date:
            self = .date(value)

        case let value as Int:
            self = .number(.int(value))

        case let value as UInt:
            self = .number(.uint(value))

        case let value as Double:
            self = .number(.double(value))

        case let value as String:
            self = .string(value)

        default:
            self = .null
        }
    }

    public var any: Any? {

        switch self {

        case .object(let object):

            var converted = [String: Any]()

            for (key, value) in object {
                converted[key] = value.any
            }

            return converted

        case .array(let value):
            return value.flatMap { $0.any }

        case .bool(let value):
            return value

        case .bytes(let value):
            return value

        case .date(let value):
            return value

        case .number(let number):

            switch number {
            case .int(let value):
                return value
            case .uint(let value):
                return value
            case .double(let value):
                return value
            }

        case .string(let value):
            return value

        case .null:
            return nil
        }
    }
}
```

**Comment by rmaes4** [comment]
👍

**Comment by linqingmo** [comment]
I think we can simply case object with mapValues.
```swift
switch self {
  case .object(let object):
    return object.mapValues { $0.convertedToAny() }
  ...
}
```

**Comment by Joannis** [comment]
@linqingmo that doesn't work in Swift 3.1

**Comment by linqingmo** [comment]
Hi @Joannis I saw Vapor 3.0 will drop Swift 3 support, and this is for node 3.0. This no need to support Swift 3 in my opion. Sorry if I am wrong.

**Comment by Joannis** [comment]
Swift 4 makes this `Node` package unnecessary, too, thanks to Codable.

**Comment by linqingmo** [comment]
@Joannis thanks.

**Comment by rmaes4** [comment]
Is there a way with the current Node package to convert to [String: Any] ?

**Comment by vzsg** [comment]
I think @valeriomazzeo's snippet should work if you copy it into your project.

**Comment by valeriomazzeo** [comment]
@rmaes4 it does work, I am using it 🙂

**Comment by valeriomazzeo** [comment]
@tanner0101 could we include this? I see no harm in it and it's very useful.

**Comment by tanner0101** [comment]
@valeriomazzeo i wouldn't be against it. although i'd prefer some naming that discourages it like `.unsafeAny` or something.

**Comment by valeriomazzeo** [comment]
I don’t have any hard feeling for a particular name. So please, include it using the name that makes more sense to you

**Comment by valeriomazzeo** [comment]
@tanner0101 I have added also the conversion from `Any`.

I may need you to double check if the `.null` case handling is correct.

This is super useful to bridge to and from the JSONSerialization system API.
